Update from https://github.com/TheFoundation/Hocker/commit/15113d7b41e433f7d58e3c65f917e9480f9c5faf

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -732,6 +732,10 @@ jobs:
       - name: NOTICE SKIP
         if: steps.check_build_baseimage.outputs.do_the_build== 'false'
         run: echo "BUILDING SKIPPED"
+      - name: send_notify
+        run: |
+             mkdir -p buildlogs|| true;git clone https://gitlab.com/the-foundation/bash-logger.git /tmp/bash-logger;(curl -s -X POST "${{ secrets.BUILDER_NOTIFICATION_URL }}"   -d '{"options": { "disable_link_previews": true,"silent":true },"text":"[ ↑_STARTING BUILD_↑ ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' |jq .message_id --raw-output > /tmp/initmsgid)||true
+             date -u +%s > /tmp/.buildstart ; 
       - name: Set up QEMU
         if: steps.check_build_baseimage.outputs.do_the_build== 'true'
         uses: docker/setup-qemu-action@v2
@@ -762,9 +766,18 @@ jobs:
              bash -c 'timediff=$(($(date -u +%s)-$(cat /tmp/.buildstart)));echo $timediff'| bash /tmp/bash-logger/log-to-influxdb2.sh "${{ secrets.LOGTOINFLUXURL }}" buildstatus FALSE buildtime "${{ secrets.LOGTOINFLUXTOKEN }}" $(echo ${{ github.job }}|sed 's/build-//g');
              (sleep 10;echo 1| bash /tmp/bash-logger/log-to-influxdb2.sh "${{ secrets.LOGTOINFLUXURL }}" buildstatus FALSE buildtime "${{ secrets.LOGTOINFLUXTOKEN }}" $(echo ${{ github.job }}|sed 's/build-//g') & )
              sleep 9;             grep ^0$ /tmp/hocker.build.result;
+      - name: notify_final
+        if: always()
+        run: |
+             bash -c 'seconds=$(($(date -u +%s)-$(cat /tmp/.buildstart)));TZ=UTC printf "AFTER: %d days %(%H hours %M minutes %S seconds)T" $((seconds/86400)) $seconds > /tmp/_send_timediff'
+             ( echo "SENDING: curl -s -X POST TOYOURTOKENURL   -d "'{"options":{"disable_link_previews":true,"silent":true},"text":"[ '$(grep -q ^0$ /tmp/hocker.build.result || echo "NOT_OK";grep -q ^0$ /tmp/hocker.build.result && echo "OK")' [ == FAILED_OR_ABORTED BUILD ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}) AFTER '$(cat /tmp/_send_timediff)' seconds  RESULT: '$(cat /tmp/hocker.build.result)'.. ","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' ; )
+             (      curl -s -X POST "${{ secrets.BUILDER_NOTIFICATION_URL }}"   -d '{"options":{"disable_link_previews":true,"silent":true},"text":"[ '$(grep -q ^0$ /tmp/hocker.build.result || echo "NOT_OK";grep -q ^0$ /tmp/hocker.build.result && echo "OK")' [ == FINISHED BUILD ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}) AFTER '$(cat /tmp/_send_timediff)' seconds  RESULT: '$(cat /tmp/hocker.build.result)'.. ","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' ; )
+             echo -n "DELETING INIT:MSG";
+             curl -s -X GET $(echo "${{ secrets.BUILDER_NOTIFICATION_URL }}" |sed 's/messages/messages_delete/g')"/"$(cat /tmp/initmsgid) ;echo  )||true
+             sleep 3
       - name: show files
-        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
-        run: bash -c "ls buildlogs/  -lh1 ; tail -n 20 buildlogs/*"
+        if: always()
+        run: bash -c "ls buildlogs/  -lh1 ; tail -n 30 buildlogs/*"
       - name: Archive production artifacts
         uses: actions/upload-artifact@v3
 #        if: failure()
@@ -882,6 +895,10 @@ jobs:
       - name: NOTICE SKIP
         if: steps.check_build_baseimage.outputs.do_the_build== 'false'
         run: echo "BUILDING SKIPPED"
+      - name: send_notify
+        run: |
+             mkdir -p buildlogs|| true;git clone https://gitlab.com/the-foundation/bash-logger.git /tmp/bash-logger;(curl -s -X POST "${{ secrets.BUILDER_NOTIFICATION_URL }}"   -d '{"options": { "disable_link_previews": true,"silent":true },"text":"[ ↑_STARTING BUILD_↑ ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' |jq .message_id --raw-output > /tmp/initmsgid)||true
+             date -u +%s > /tmp/.buildstart ; 
       - name: Set up QEMU
         if: steps.check_build_baseimage.outputs.do_the_build== 'true'
         uses: docker/setup-qemu-action@v2
@@ -912,9 +929,18 @@ jobs:
              bash -c 'timediff=$(($(date -u +%s)-$(cat /tmp/.buildstart)));echo $timediff'| bash /tmp/bash-logger/log-to-influxdb2.sh "${{ secrets.LOGTOINFLUXURL }}" buildstatus FALSE buildtime "${{ secrets.LOGTOINFLUXTOKEN }}" $(echo ${{ github.job }}|sed 's/build-//g');
              (sleep 10;echo 1| bash /tmp/bash-logger/log-to-influxdb2.sh "${{ secrets.LOGTOINFLUXURL }}" buildstatus FALSE buildtime "${{ secrets.LOGTOINFLUXTOKEN }}" $(echo ${{ github.job }}|sed 's/build-//g') & )
              sleep 9;             grep ^0$ /tmp/hocker.build.result;
+      - name: notify_final
+        if: always()
+        run: |
+             bash -c 'seconds=$(($(date -u +%s)-$(cat /tmp/.buildstart)));TZ=UTC printf "AFTER: %d days %(%H hours %M minutes %S seconds)T" $((seconds/86400)) $seconds > /tmp/_send_timediff'
+             ( echo "SENDING: curl -s -X POST TOYOURTOKENURL   -d "'{"options":{"disable_link_previews":true,"silent":true},"text":"[ '$(grep -q ^0$ /tmp/hocker.build.result || echo "NOT_OK";grep -q ^0$ /tmp/hocker.build.result && echo "OK")' [ == FAILED_OR_ABORTED BUILD ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}) AFTER '$(cat /tmp/_send_timediff)' seconds  RESULT: '$(cat /tmp/hocker.build.result)'.. ","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' ; )
+             (      curl -s -X POST "${{ secrets.BUILDER_NOTIFICATION_URL }}"   -d '{"options":{"disable_link_previews":true,"silent":true},"text":"[ '$(grep -q ^0$ /tmp/hocker.build.result || echo "NOT_OK";grep -q ^0$ /tmp/hocker.build.result && echo "OK")' [ == FINISHED BUILD ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}) AFTER '$(cat /tmp/_send_timediff)' seconds  RESULT: '$(cat /tmp/hocker.build.result)'.. ","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' ; )
+             echo -n "DELETING INIT:MSG";
+             curl -s -X GET $(echo "${{ secrets.BUILDER_NOTIFICATION_URL }}" |sed 's/messages/messages_delete/g')"/"$(cat /tmp/initmsgid) ;echo  )||true
+             sleep 3
       - name: show files
-        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
-        run: bash -c "ls buildlogs/  -lh1 ; tail -n 20 buildlogs/*"
+        if: always()
+        run: bash -c "ls buildlogs/  -lh1 ; tail -n 30 buildlogs/*"
       - name: Archive production artifacts
         uses: actions/upload-artifact@v3
 #        if: failure()
@@ -1030,6 +1056,10 @@ jobs:
       - name: NOTICE SKIP
         if: steps.check_build_baseimage.outputs.do_the_build== 'false'
         run: echo "BUILDING SKIPPED"
+      - name: send_notify
+        run: |
+             mkdir -p buildlogs|| true;git clone https://gitlab.com/the-foundation/bash-logger.git /tmp/bash-logger;(curl -s -X POST "${{ secrets.BUILDER_NOTIFICATION_URL }}"   -d '{"options": { "disable_link_previews": true,"silent":true },"text":"[ ↑_STARTING BUILD_↑ ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' |jq .message_id --raw-output > /tmp/initmsgid)||true
+             date -u +%s > /tmp/.buildstart ; 
       - name: Set up QEMU
         if: steps.check_build_baseimage.outputs.do_the_build== 'true'
         uses: docker/setup-qemu-action@v2
@@ -1060,9 +1090,18 @@ jobs:
              bash -c 'timediff=$(($(date -u +%s)-$(cat /tmp/.buildstart)));echo $timediff'| bash /tmp/bash-logger/log-to-influxdb2.sh "${{ secrets.LOGTOINFLUXURL }}" buildstatus FALSE buildtime "${{ secrets.LOGTOINFLUXTOKEN }}" $(echo ${{ github.job }}|sed 's/build-//g');
              (sleep 10;echo 1| bash /tmp/bash-logger/log-to-influxdb2.sh "${{ secrets.LOGTOINFLUXURL }}" buildstatus FALSE buildtime "${{ secrets.LOGTOINFLUXTOKEN }}" $(echo ${{ github.job }}|sed 's/build-//g') & )
              sleep 9;             grep ^0$ /tmp/hocker.build.result;
+      - name: notify_final
+        if: always()
+        run: |
+             bash -c 'seconds=$(($(date -u +%s)-$(cat /tmp/.buildstart)));TZ=UTC printf "AFTER: %d days %(%H hours %M minutes %S seconds)T" $((seconds/86400)) $seconds > /tmp/_send_timediff'
+             ( echo "SENDING: curl -s -X POST TOYOURTOKENURL   -d "'{"options":{"disable_link_previews":true,"silent":true},"text":"[ '$(grep -q ^0$ /tmp/hocker.build.result || echo "NOT_OK";grep -q ^0$ /tmp/hocker.build.result && echo "OK")' [ == FAILED_OR_ABORTED BUILD ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}) AFTER '$(cat /tmp/_send_timediff)' seconds  RESULT: '$(cat /tmp/hocker.build.result)'.. ","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' ; )
+             (      curl -s -X POST "${{ secrets.BUILDER_NOTIFICATION_URL }}"   -d '{"options":{"disable_link_previews":true,"silent":true},"text":"[ '$(grep -q ^0$ /tmp/hocker.build.result || echo "NOT_OK";grep -q ^0$ /tmp/hocker.build.result && echo "OK")' [ == FINISHED BUILD ](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}) AFTER '$(cat /tmp/_send_timediff)' seconds  RESULT: '$(cat /tmp/hocker.build.result)'.. ","origin":"'$(echo "${{ github.job }}@${{ github.repository_owner }}/${{ github.event.repository.name }}"|sed 's/build-//g')'"}' ; )
+             echo -n "DELETING INIT:MSG";
+             curl -s -X GET $(echo "${{ secrets.BUILDER_NOTIFICATION_URL }}" |sed 's/messages/messages_delete/g')"/"$(cat /tmp/initmsgid) ;echo  )||true
+             sleep 3
       - name: show files
-        if: steps.check_build_baseimage.outputs.do_the_build== 'true'
-        run: bash -c "ls buildlogs/  -lh1 ; tail -n 20 buildlogs/*"
+        if: always()
+        run: bash -c "ls buildlogs/  -lh1 ; tail -n 30 buildlogs/*"
       - name: Archive production artifacts
         uses: actions/upload-artifact@v3
 #        if: failure()
